# Generated by Django 4.0.1 on 2022-01-24 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCollections',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('date_created_on', models.DateTimeField(auto_now_add=True)),
                ('date_updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('collection_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_collection_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
