# Generated by Django 4.0.1 on 2022-01-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('genre', models.CharField(db_index=True, max_length=250)),
                ('collection_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_collection_creator', to='movie_collections.moviecollections')),
            ],
        ),
    ]
